from . import sale_order_sever_copy
from . import sale_order
from . import sale_order_line_inherit
from . import sale_order_override_validation
from . import product_template_inherit
from . import pancake_sync_helper
from . import deposit_confirm_wizard
from . import account_move
from . import account_payment_register
from . import account_payment
from . import dashboard
from . import google_sheet_push