{
    'name': 'DAC Attendance',
    'version': '4.0',
    'category': '1. Duy An ERP',
    'author': 'Huỳnh Quốc An',
    'sequence': 10,
    'summary': 'Hệ thống chấm công DAC: Dashboard nhân viên/quản lý, xin nghỉ phép, điều chỉnh chấm công',
    'description': '',
    'depends': ['base', 'web', 'hr', 'hr_attendance'],
    'installable': True,
    'auto_install': False,
    'application': False,
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'views/employee_attendance_config_views.xml',
        'views/attendance_kiosk_views.xml',
        'views/dac_attendance_leave_views.xml',
        'views/dac_attendance_amendment_views.xml',
        'views/dashboard_actions.xml',
        'views/attendance_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # Existing
            'dac_attendance/static/src/js/attendance_systray.js',
            'dac_attendance/static/src/js/attendance_camera_dialog.js',
            'dac_attendance/static/src/xml/attendance_systray.xml',
            'dac_attendance/static/src/xml/attendance_camera_dialog.xml',
            'dac_attendance/static/src/scss/attendance_systray.scss',
            'dac_attendance/static/src/scss/attendance.scss',
            # New sub-components
            'dac_attendance/static/src/js/components/attendance_mini_calendar.js',
            'dac_attendance/static/src/js/components/leave_request_dialog.js',
            'dac_attendance/static/src/js/components/amendment_request_dialog.js',
            'dac_attendance/static/src/xml/components/attendance_mini_calendar.xml',
            'dac_attendance/static/src/xml/components/leave_request_dialog.xml',
            'dac_attendance/static/src/xml/components/amendment_request_dialog.xml',
            # New dashboards
            'dac_attendance/static/src/js/employee_dashboard.js',
            'dac_attendance/static/src/js/manager_dashboard.js',
            'dac_attendance/static/src/xml/employee_dashboard.xml',
            'dac_attendance/static/src/xml/manager_dashboard.xml',
            'dac_attendance/static/src/scss/attendance_mini_calendar.scss',
            'dac_attendance/static/src/scss/employee_dashboard.scss',
            'dac_attendance/static/src/scss/manager_dashboard.scss',
        ],
    },
    'license': 'LGPL-3',
}
